# Generated by Django 5.1.4 on 2025-09-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file', null=True, upload_to='food_items/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
    ]
