# Generated by Django 5.1.4 on 2025-09-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_user_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.fooditem'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='store.category'),
        ),
        migrations.AlterField(
            model_name='pizzaoption',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_options', to='store.fooditem'),
        ),
    ]
