# Generated by Django 5.1.4 on 2025-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_bagitem_food_item_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='item_category',
            field=models.CharField(blank=True, help_text='Category of the food item when ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='bagitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='Name of the food item when ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='bagitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the food item when ordered', max_digits=10, null=True),
        ),
    ]
