# Generated by Django 5.1.4 on 2025-09-21 12:39

from django.db import migrations


def populate_bagitem_data(apps, schema_editor):
    """Populate the new fields in existing BagItem records."""
    BagItem = apps.get_model('store', 'BagItem')
    
    for bag_item in BagItem.objects.filter(food_item__isnull=False):
        if bag_item.food_item:
            bag_item.item_name = bag_item.food_item.name
            bag_item.item_price = bag_item.food_item.price
            if bag_item.food_item.category:
                bag_item.item_category = bag_item.food_item.category.name
            bag_item.save()


def reverse_populate_bagitem_data(apps, schema_editor):
    """Reverse migration - clear the stored data."""
    BagItem = apps.get_model('store', 'BagItem')
    BagItem.objects.all().update(
        item_name='',
        item_price=None,
        item_category=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_bagitem_item_category_bagitem_item_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_bagitem_data, reverse_populate_bagitem_data),
    ]
