# Generated by Django 5.1.4 on 2025-09-21 12:41

from django.db import migrations


def create_uncategorized_category(apps, schema_editor):
    """Create an 'Uncategorized' category and assign it to food items with NULL categories."""
    Category = apps.get_model('store', 'Category')
    FoodItem = apps.get_model('store', 'FoodItem')
    
    # Create the Uncategorized category
    uncategorized_category, created = Category.objects.get_or_create(
        name="Uncategorized",
        defaults={'name': 'Uncategorized'}
    )
    
    # Assign all food items with NULL categories to the Uncategorized category
    FoodItem.objects.filter(category__isnull=True).update(category=uncategorized_category)


def reverse_create_uncategorized_category(apps, schema_editor):
    """Reverse migration - set category to NULL for items in Uncategorized category."""
    Category = apps.get_model('store', 'Category')
    FoodItem = apps.get_model('store', 'FoodItem')
    
    try:
        uncategorized_category = Category.objects.get(name="Uncategorized")
        FoodItem.objects.filter(category=uncategorized_category).update(category=None)
        uncategorized_category.delete()
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20250921_1239'),
    ]

    operations = [
        migrations.RunPython(create_uncategorized_category, reverse_create_uncategorized_category),
    ]
