# Generated by Django 5.1.4 on 2025-09-21 12:46

from django.db import migrations, models
import django.db.models.deletion


def clean_bag_items_with_null_food_items(apps, schema_editor):
    """Remove any BagItem records that have NULL food_item references."""
    BagItem = apps.get_model('store', 'BagItem')
    # Delete any BagItems that have NULL food_item references
    BagItem.objects.filter(food_item__isnull=True).delete()


def reverse_clean_bag_items_with_null_food_items(apps, schema_editor):
    """Reverse migration - nothing to do."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20250921_1241'),
    ]

    operations = [
        migrations.RunPython(clean_bag_items_with_null_food_items, reverse_clean_bag_items_with_null_food_items),
        migrations.AlterField(
            model_name='bagitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fooditem'),
        ),
    ]
