# Generated by Django 5.1.4 on 2025-09-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.fooditem'),
        ),
    ]
