# Generated by Django 5.1.4 on 2025-09-21 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_inventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
