# Generated by Django 5.1.4 on 2025-09-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_inventoryitem_created_by_inventoryitem_updated_by'),
    ]

    operations = [
    ]
