# Generated by Django 5.1.4 on 2025-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_fooditem_name'),
    ]

    operations = [
        # Rename quantity to portions in FoodItem
        migrations.RenameField(
            model_name='fooditem',
            old_name='quantity',
            new_name='portions',
        ),
        # Rename quantity to portions in BagItem
        migrations.RenameField(
            model_name='bagitem',
            old_name='quantity',
            new_name='portions',
        ),
        # Update help text for price field
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per portion', max_digits=10),
        ),
        # Update help text for portions field
        migrations.AlterField(
            model_name='fooditem',
            name='portions',
            field=models.PositiveIntegerField(default=0, help_text='Available portions in stock'),
        ),
        # Update help text for BagItem portions
        migrations.AlterField(
            model_name='bagitem',
            name='portions',
            field=models.PositiveIntegerField(default=1, help_text='Number of portions ordered'),
        ),
        # Update help text for BagItem plates
        migrations.AlterField(
            model_name='bagitem',
            name='plates',
            field=models.PositiveIntegerField(default=0, help_text='Number of plates (only for food category items)'),
        ),
        # Update help text for item_price
        migrations.AlterField(
            model_name='bagitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per portion when ordered', max_digits=10, null=True),
        ),
    ]
