# Generated by Django 5.2.6 on 2025-09-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_order_constraints'),
        ('store', '0021_update_quantity_to_portions'),
    ]

    operations = [
    ]
