# Generated by Django 5.1.4 on 2025-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_add_pos_only_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='pos_only',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=10),
        ),
    ]
