# Generated by Django 5.1.4 on 2025-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_fooditem_created_by_fooditem_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the order was actually delivered', null=True),
        ),
    ]
