# Generated by Django 5.1.4 on 2025-10-11 11:24

from django.db import migrations
from decimal import Decimal


def fix_service_charge(apps, schema_editor):
    """Fix service charge for existing orders to match checkout page (₦500)."""
    Order = apps.get_model('store', 'Order')
    
    # Update all orders that have service_charge = 100 to 500
    orders_to_fix = Order.objects.filter(service_charge=Decimal('100.00'))
    updated_count = orders_to_fix.update(service_charge=Decimal('500.00'))
    
    print(f"Updated {updated_count} orders with incorrect service charge")


def reverse_fix_service_charge(apps, schema_editor):
    """Reverse the service charge fix."""
    Order = apps.get_model('store', 'Order')
    
    # Revert orders back to 100 (though this shouldn't be needed)
    orders_to_revert = Order.objects.filter(service_charge=Decimal('500.00'))
    reverted_count = orders_to_revert.update(service_charge=Decimal('100.00'))
    
    print(f"Reverted {reverted_count} orders service charge")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_payment_order'),
    ]

    operations = [
        migrations.RunPython(fix_service_charge, reverse_fix_service_charge),
    ]
