# Generated by Django 5.1.4 on 2025-10-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_fix_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT amount in Naira', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='VAT percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
