# Generated by Django 5.1.4 on 2025-10-12 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_add_vat_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('service_charge', 'Service Charge'), ('vat_percentage', 'VAT Percentage'), ('delivery_fee_base', 'Base Delivery Fee'), ('plate_fee', 'Plate Fee')], max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Setting value', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['setting_type'],
            },
        ),
    ]
