# Generated by Django 5.1.4 on 2025-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
