# Generated by Django 5.1.4 on 2025-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Plain text password for admin viewing (not used for authentication)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
