# Generated by Django 5.1.4 on 2025-09-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_plain_password_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
